language: python
python:
  - '3.3'
  - '3.5'
  - '2.7'
matrix:
  include:
  - python: "2.7"
    env: TEST_SUITE=suite_2_7
  - python: "3.3"
    env: TEST_SUITE=suite_3_3
  - python: "pypy"
    env: TEST_SUITE=suite_pypy
script: ./testsuite3.py $TEST_SUITE